name: CI
on:
  push: {branches: [main]}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-mingw:
    runs-on: windows-latest
    name: mingw-${{ matrix.arch }} - ${{ matrix.cffi }} - ${{ matrix.distutils}} distutils
    strategy:
      fail-fast: false
      matrix:
        cffi: ["cffi<1.16", "cffi>=1.16.0"]
        arch: ["i686", "x86_64"]
        distutils: ["stdlib", "local"]
    steps:
      - uses: actions/checkout@v3
      - name: Install MSys2 and dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.arch == 'x86_64' && 'MINGW64' || 'MINGW32' }}
          install: >-
            git
            mingw-w64-${{ matrix.arch }}-python
            mingw-w64-${{ matrix.arch }}-python-pip
            mingw-w64-${{ matrix.arch }}-openssl
            mingw-w64-${{ matrix.arch }}-toolchain
      - name: Debug Info
        shell: msys2 {0}
        env:
          SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils }}
        run: |
          python -m pip install -U pip setuptools wheel
          echo "$(which python) -- $(python -VV)"
          echo "$(which pip) -- $(pip -VV)"
          python -c 'import os, sys; print(os.name, sys.platform, getattr(sys, "abiflags", None))'
          python -c 'import importlib.machinery as im; print(im.all_suffixes())'
          python -m pip -V
          python -m pip list
      - name: Test
        shell: msys2 {0}
        run: |
          python -m pip install -U "${{ matrix.cffi}}"
          python -m pip list
